### ISSUE TITLE
App is getting crashed while running in background for a long time

### ISSUE THREAD

**Issue by neelayak** [rekab-app/background_locator#107]
I am getting this exception if i let the app run in the foreground 
`java.lang.RuntimeException: Unable to start receiver rekab.app.background_locator.BootBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2739)
	at android.app.ActivityThread.access$1800(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
	at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerLocator(BackgroundLocatorPlugin.kt:103)
	at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerAfterBoot(BackgroundLocatorPlugin.kt:263)
	at rekab.app.background_locator.BootBroadcastReceiver.onReceive(BootBroadcastReceiver.kt:10)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
	... 8 more`

Any idea why it is happening this is not coming when i am compiling the app it happens when i keep the app running in foreground.

**Comment by ThiagoCortez81** [comment]
This is also happening to me. I just edited the code of this repo and now I'm testing if all worked... this issue also was happening when I was trying to init the service when the devices finish reboot.

If all works great, I'll make a pull-request soon.

**Comment by neelayak** [comment]
Sounds great ,thx for letting me know about this

**Comment by neelayak** [comment]
@ThiagoCortez81  Any update on this bug??

**Comment by ThiagoCortez81** [comment]
@neelayak not so far man... :(

**Comment by neelayak** [comment]
Hey i am getting this error in the release build 
`Caused by java.lang.IllegalArgumentException
Given work is not active: JobWorkItem{id=1 intent=Intent { flg=0x10 cmp=com.familytrack.angelsos/rekab.app.background_locator.LocatorBroadcastReceiver (has extras) } dcount=1}
android.app.job.JobParameters.completeWork (JobParameters.java:268)
androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete (JobIntentService.java:268)
androidx.core.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:394)
androidx.core.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:383)
android.os.AsyncTask$2.call (AsyncTask.java:333)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)`
i got this via firebase hope this helps you in fixing this.

**Comment by mehdok** [comment]
@neelayak @ThiagoCortez81 
Hi guys, thank you for reporting an issue, and thank you for your patient.

These kind of bug is really hard to find, because I have to run the app for a long time, and I did that several times without any problem. Basically I can not regenerate this issue and without regenerating it there is no way to fix it. So I would be more than happy to hear your ideas about this bug, about how to reproduce it or it's cause or even a solution;

**Comment by steinmetz** [comment]
Hi all,
I am also getting this problem in production and it happens only with Android 10. If I find out what is happening I will report here.

**Comment by mehdok** [comment]
Hi @mehdok 
Thank you for reporting.

Do you have any log, code sample, or any idea? anything would be appreciated;

**Comment by steinmetz** [comment]
No idea so far... I am wondering if it could be something related to the permission system that has changed on Android 10 and 11.
The only log I got is this, but it is generic and doesn't help so much:
![image](https://user-images.githubusercontent.com/3587083/94999451-cceb6680-05b9-11eb-9e54-f19bbb73a964.png)

I was reading this documentation:
"To support the additional control that users have over an app's access to location information, Android 10 introduces the ACCESS_BACKGROUND_LOCATION permission."

Link: https://developer.android.com/about/versions/10/privacy/changes

Maybe this could be the one problem, but the logs say nothing about it :/
