### ISSUE TITLE
Stop on App Terminate

### ISSUE THREAD

**Issue by fre391** [rekab-app/background_locator#133]
I try to implement a feature to stop the location Updates when the app exits. When using the following changes and retarting the app I get the following error:

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fd28c5b u0 com.example.background_locator_example/rekab.app.background_locator.IsolateHolderService}

<service android:name="rekab.app.background_locator.LocatorService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="true"
            android:stopWithTask="true"/>

        <service android:name="rekab.app.background_locator.IsolateHolderService"
            android:permission="android.permission.FOREGROUND_SERVICE"
            android:exported="true"
            android:stopWithTask="true"/>

I guess it is caused, because the app termination (before restarting) is not handled correctly:
EGLNativeWindowType 0x79434d1010 disconnect failed

So, I really have some doubts that all services are stopped correctly. But I don't really yet.:-)

I would appreciate any help. Thank you so much for your package...Its great.

**Comment by mehdok** [comment]
Hi @fre391,
Thanks for opening an issue!
Please answer following questions:

> When using the following changes and retarting the app 
- How did you restart the app?
- Did you test with example app? If not please share some code.
- How did you terminate the app?
- Any extra info and log would help a lot.

**Comment by lexririmike** [comment]
Hi @fre391 and @mehdok,

I faced the same issue. 
My app ran for 3 days straight and suddenly stopped working.
On checking the log, I got the above message but after running adb logcat on rekab.app.background_locator. I got the following error.  `Unable to start receiver rekab.app.background_locator.BootBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>`

**Comment by fre391** [comment]
Hey,

no for me its. different scenario. In general I would like to achieve, that the location service will run as long as the app is running (in foreground but also in background), but I would like to stop the services, when the user exits the app (when swiping out from the task manager). As log as the user will stop the service before exit the app, everything is working expected. The problem occurs, if the user does NOT STOP the service before exiting the app. 

I noticed that  the dispose function of the main activity is not executed. I guess, this causes the trouble, when restarting the app again. I think, if unRegisterLocationUpdate would be called in dispose the problem would be gone.

I noticed the issue by running the example app, but I modified the two services by adding "stopWithTask" in the manifest as mentioned in the wiki. Temporarilly I also tried to additionally set the attribute also for the receiver, but later I removed it again.  

Meanwhile I have changed the example app in order to simply (from my point of view). I use two files now, 
main.dart and location_callback_handler.dart (refer below):

main.dart:

```
import 'dart:async';
import 'dart:ui';

import 'package:background_locator/background_locator.dart';
import 'package:background_locator/settings/android_settings.dart';
import 'package:background_locator/settings/ios_settings.dart';
import 'package:background_locator/settings/locator_settings.dart';
import 'package:flutter/material.dart';
import 'package:location_permissions/location_permissions.dart';

import 'location_callback_handler.dart';

import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String logStr = '';
  bool isRunning = false;
  List<LatLng> points = List();
  int _counter = 0;

  @override
  void initState() {
    super.initState();

    LocationCallbackHandler.getPort().listen(
      (dynamic data) async {
        if (data == null) return;
        await BackgroundLocator.updateNotificationText(
            title: "new location received",
            msg: "${DateTime.now()}",
            bigMsg: "${data.latitude}, ${data.longitude}");

        setState(() {
          if (data != null) {
            print("location found");
            logStr += '($_counter) ${data.latitude}, ${data.longitude}, ${data.isMocked}, ' +
                DateTime.now().hour.toString() +
                ":" +
                DateTime.now().minute.toString() +
                ":" +
                DateTime.now().second.toString() +
                "\n";
            var point = LatLng(data.latitude, data.longitude);
            points.add(point);
            _counter++;
          }
        });
      },
    );
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    print('Initializing...');
    await BackgroundLocator.initialize();
    print('Initialization done');
    final _isRunning = await BackgroundLocator.isServiceRunning();
    setState(() {
      isRunning = _isRunning;
    });
    print('Running ${isRunning.toString()}');
  }

  void _onStart() async {
    if (await _checkLocationPermission()) {
      _startLocator();
      final _isRunning = await BackgroundLocator.isServiceRunning();
      setState(() {
        isRunning = _isRunning;
      });
      print('Running ${isRunning.toString()}');
    } else {
      // show error
    }
  }

  Future<bool> _checkLocationPermission() async {
    final access = await LocationPermissions().checkPermissionStatus();
    switch (access) {
      case PermissionStatus.unknown:
      case PermissionStatus.denied:
      case PermissionStatus.restricted:
        final permission = await LocationPermissions().requestPermissions(
          permissionLevel: LocationPermissionLevel.locationAlways,
        );
        if (permission == PermissionStatus.granted) {
          return true;
        } else {
          return false;
        }
        break;
      case PermissionStatus.granted:
        return true;
        break;
      default:
        return false;
        break;
    }
  }

  void _startLocator() {
    Map<String, dynamic> data = {'countInit': 1};
    BackgroundLocator.registerLocationUpdate(LocationCallbackHandler.callback,
        initCallback: LocationCallbackHandler.initCallback,
        initDataCallback: data,
        disposeCallback: LocationCallbackHandler.disposeCallback,
        autoStop: false,
        iosSettings: IOSSettings(
            showsBackgroundLocationIndicator: true,
            accuracy: LocationAccuracy.BALANCED,
            distanceFilter: 0),
        androidSettings: AndroidSettings(
            accuracy: LocationAccuracy.BALANCED,
            interval: 5,
            distanceFilter: 0,
            androidNotificationSettings: AndroidNotificationSettings(
                notificationChannelName: 'App Location tracking',
                notificationTitle: 'App Location Tracking',
                notificationMsg: 'Track location in background',
                notificationBigMsg:
                    'App uses Background location to keep the app up-tp-date with your location. This is required for main features to work properly when App is not running.',
                notificationIcon: '',
                notificationIconColor: Colors.grey,
                notificationTapCallback: LocationCallbackHandler.notificationCallback)));
  }

  void _onStop() async {
    BackgroundLocator.unRegisterLocationUpdate();
    final _isRunning = await BackgroundLocator.isServiceRunning();

    setState(() {
      isRunning = _isRunning;
    });
    print('Running ${isRunning.toString()}');
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(),
      darkTheme: ThemeData.dark(),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('App Background Location'),
        ),
        body: Container(
          width: double.maxFinite,
          padding: const EdgeInsets.all(22),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    RaisedButton(
                      padding: EdgeInsets.all(20),
                      child: (!isRunning) ? Text("START") : Text("STARTED"),
                      onPressed: (!isRunning) ? _onStart : null,
                    ),
                    Container(width: 20),
                    RaisedButton(
                      padding: EdgeInsets.all(20),
                      child: (isRunning) ? Text("STOP") : Text("STOPPED"),
                      onPressed: (isRunning) ? _onStop : null,
                    ),
                  ],
                ),

                Divider(),
                Text("Status: " + (isRunning ? "RUNNING" : "STOPPED")),
                Divider(),
                (points.length > 0)
                    ? Container(
                        height: 250,
                        child: FlutterMap(
                          options: MapOptions(
                            center: LatLng(51.9, 8.4),
                            zoom: 10.0,
                          ),
                          layers: [
                            TileLayerOptions(
                              urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                              subdomains: ['a', 'b', 'c'],
                              tileProvider: NonCachingNetworkTileProvider(),
                            ),
                            PolylineLayerOptions(
                              polylines: [
                                Polyline(points: points, strokeWidth: 4.0, color: Colors.purple),
                              ],
                            ),
                          ],
                        ),
                      )
                    : Container(
                        height: 0,
                      ),
                Divider(),
                Text(logStr, style: TextStyle(fontSize: 12)),
                //getButton(),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    // unfortunaltely not called
    BackgroundLocator.unRegisterLocationUpdate();
    super.dispose();
  }
}
```


location_callback_handler.dart:

```
import 'dart:async';
import 'dart:isolate';
import 'dart:ui';

import 'package:background_locator/location_dto.dart';

class LocationCallbackHandler {
  static const String isolateName = 'LocatorIsolate';

  static ReceivePort getPort() {
    ReceivePort port = ReceivePort();
    if (IsolateNameServer.lookupPortByName(isolateName) != null) {
      IsolateNameServer.removePortNameMapping(isolateName);
    }
    IsolateNameServer.registerPortWithName(port.sendPort, isolateName);
    return port;
  }

  static Future<void> initCallback(Map<dynamic, dynamic> params) async {
    final SendPort send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(null);
  }

  static Future<void> disposeCallback() async {
    final SendPort send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(null);
    //IsolateNameServer.removePortNameMapping(isolateName);
  }

  static Future<void> callback(LocationDto locationDto) async {
    final SendPort send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(locationDto);
  }

  static Future<void> notificationCallback() async {
    print('***notificationCallback');
  }
}
```

This is a typical debug output of the described scenario:

First time run:

```
Launching lib/main.dart on Pixel 3a in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:50825/nAKnLZkohzw=/ws
I/flutter (17726): Initializing...
I/flutter (17726): Initialization done
I/flutter (17726): Running false
I/flutter (17726): Running true
I/flutter (17726): location found
I/flutter (17726): location found
W/libEGL  (17726): EGLNativeWindowType 0x7dba58d010 disconnect failed
```

Second time run:

```
W/ActivityThread(17726): handleWindowVisibility: no activity for token android.os.BinderProxy@9536b77
I/Choreographer(17726): Skipped 32 frames!  The application may be doing too much work on its main thread.
I/flutter (17726): Initializing...
I/flutter (17726): Initialization done
I/flutter (17726): Running true
I/flutter (17726): location found
D/AndroidRuntime(17726): Shutting down VM
E/AndroidRuntime(17726): FATAL EXCEPTION: main
E/AndroidRuntime(17726): Process: com.example.background_locator_example, PID: 17726
E/AndroidRuntime(17726): java.lang.RuntimeException: Unable to start service rekab.app.background_locator.IsolateHolderService@a7b466b with Intent { act=UPDATE_NOTIFICATION cmp=com.example.background_locator_example/rekab.app.background_locator.IsolateHolderService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=app.rekab/locator_plugin pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 vis=PRIVATE)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
E/AndroidRuntime(17726): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
E/AndroidRuntime(17726): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17726): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(17726): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17726): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(17726): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(17726): Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=app.rekab/locator_plugin pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 vis=PRIVATE)
E/AndroidRuntime(17726): 	at android.app.NotificationManager.fixNotification(NotificationManager.java:516)
E/AndroidRuntime(17726): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:495)
E/AndroidRuntime(17726): 	at android.app.NotificationManager.notify(NotificationManager.java:444)
E/AndroidRuntime(17726): 	at android.app.NotificationManager.notify(NotificationManager.java:420)
E/AndroidRuntime(17726): 	at rekab.app.background_locator.IsolateHolderService.updateNotification(IsolateHolderService.kt:233)
E/AndroidRuntime(17726): 	at rekab.app.background_locator.IsolateHolderService.onStartCommand(IsolateHolderService.kt:182)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
E/AndroidRuntime(17726): 	... 8 more
I/Process (17726): Sending signal. PID: 17726 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by fre391** [comment]
I found a workaround for this issue as follows:

```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    print(state);
    bool _wasrunning = await BackgroundLocator.isServiceRunning();
    if (_wasrunning) _onStop();
    if (state != AppLifecycleState.detached) {
      await Future.delayed(const Duration(seconds: 10), () {
        if (_wasrunning) _onStart();
      });
    }
  }
```

Well, I know, its **not** the perfect solution, but at least this can handle the situation from outside the plugin.
The situation is, that the service is not stopped, when the app exits. Also dispose() is not called. 

With the WidgetsBindingObserver the AppLifecycleState will be monitored. The issue here is, that didChangeAppLifecycleState will not wait for awaits when the app gets detached. Therefore I stop the services whenever the state is changing and start it again after a certain time (ex 10 seconds) - except the app gets detached. Well, this assumes that the user will not wait longer than 10 seconds to finally swipe the app from the task manager, which is, of course, not a stable assumption.  I also have not tested, if it also works with IOS.

However, It would be great, if you could find a way for the package to handle with that scenario. I think, in a lot of real life situations its not accepted, that the location service is running forever and esp. also  after device boot. So, it would be great, if you could think about it...Thank you so much again and good luck.

**Comment by mehdok** [comment]
@fre391 Thank you for finding a workaround for this problem; I will try to fix this on Plugin side;

**Comment by ovaldi** [comment]
Same issue +1

**Comment by joranmulderij** [comment]
![Screenshot](https://user-images.githubusercontent.com/66296620/97825513-addb1400-1ce0-11eb-88c8-8c9d1a3af07e.png)
This is a screenshot of a stack-trace from firebase crashlytics.
I'm pretty sure its this issue.
Hopefully it helps.



    rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$initializeService (BackgroundLocatorPlugin.java)
    rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$initializeService (BackgroundLocatorPlugin.java)
    rekab.app.background_locator.BootBroadcastReceiver.onReceive (BootBroadcastReceiver.java)
    android.app.ActivityThread.handleReceiver (ActivityThread.java:2749)
    android.app.ActivityThread.access$1800 (ActivityThread.java:163)
    android.app.ActivityThread$H.handleMessage (ActivityThread.java:1435)
    android.os.Handler.dispatchMessage (Handler.java:102)
    android.os.Looper.loop (Looper.java:135)
    android.app.ActivityThread.main (ActivityThread.java:5536)
    java.lang.reflect.Method.invoke (Method.java)
    java.lang.reflect.Method.invoke (Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1397)
    com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1192)

**Comment by terenceponce** [comment]
Is there any updates on this? Would be great to have a solution on this.

**Comment by mehdok** [comment]
Sorry, not yet.
