### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.

### ISSUE THREAD

**Issue by saravananmnm** [rekab-app/background_locator#144]
E/flutter (14319): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
E/flutter (14319): Receiver: null
E/flutter (14319): Tried calling: toRawHandle()
E/flutter (14319): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (14319): #1      SettingsUtil._getCommonArgumentsMap (package:background_locator/utils/settings_util.dart:40:55)
E/flutter (14319): #2      SettingsUtil.getArgumentsMap (package:background_locator/utils/settings_util.dart:17:18)
E/flutter (14319): #3      BackgroundLocator.registerLocationUpdate (package:background_locator/background_locator.dart:37:31)
E/flutter (14319): #4      CustomLocationUpdates.startLocation (package:courier_alliance/src/service/locationUpdate.dart:83:26)
E/flutter (14319): #5      CustomLocationUpdates.checkForAutoLocation (package:courier_alliance/src/service/locationUpdate.dart:53:7)

**Comment by mehdok** [comment]
Hi @saravananmnm 
Thank you for opening an issue;

It would be nice if you could provide some code;

**Comment by TomasWeg** [comment]
@mehdok here i got the same error

**Comment by TomasWeg** [comment]
@mehdok 
Here is MY code:
```
await BackgroundLocator.initialize();
        await BackgroundLocator.registerLocationUpdate(
          _locationUpdated,
          initCallback: (data) {
            print("Init callback called with data: $data");
          },
          autoStop: false,
          androidSettings: AndroidSettings(
            accuracy: LocationAccuracy.NAVIGATION,
            interval: 5,
            distanceFilter: 0,
            androidNotificationSettings: AndroidNotificationSettings(
              
            ),
          ),
          iosSettings: IOSSettings(
            accuracy: LocationAccuracy.NAVIGATION,
            showsBackgroundLocationIndicator: true
          )
        );
```

**Comment by Jonas-C** [comment]
Without being 100% sure, I believe that this is caused by passing in a non-static function to `BackgroundLocator.registerLocationUpdate`. `PluginUtilities.getCallbackHandle` expects a top-level or static function, and will return null if served something else. 

In your case, I'd assume that you'd need to make your `initCallback` function static, and possibly even the callback itself if it's not already static.

**Comment by sspatari** [comment]
> Without being 100% sure, I believe that this is caused by passing in a non-static function to `BackgroundLocator.registerLocationUpdate`. `PluginUtilities.getCallbackHandle` expects a top-level or static function, and will return null if served something else.
> 
> In your case, I'd assume that you'd need to make your `initCallback` function static, and possibly even the callback itself if it's not already static.

yeap that's right
