### ISSUE TITLE
App crash : java.lang.RuntimeException

### ISSUE THREAD

**Issue by Wian-TMC** [rekab-app/background_locator#152]
The error occurred on Android 5.1 (SDK 22)

The crash occurs when starting the app. The logs show the following:

```
java.lang.RuntimeException:
at android.app.ActivityThread.handleReceiver (ActivityThread.java:2845)
at android.app.ActivityThread.access$1700 (ActivityThread.java:178)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1547)
at android.os.Handler.dispatchMessage (Handler.java:111)
at android.os.Looper.loop (Looper.java:194)
at android.app.ActivityThread.main (ActivityThread.java:5637)
at java.lang.reflect.Method.invoke (Method.java)
at java.lang.reflect.Method.invoke (Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:754)
Caused by: kotlin.TypeCastException:
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$initializeService (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$isRegisterLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$registerLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$removeLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.getAccuracy (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.getCallbackHandle (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.getLocationRequest (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.initializeService (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.isRegisterLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerAfterBoot (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.removeLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.setCallbackDispatcherHandle (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.setCallbackHandle (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.setDataCallback (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$initializeService (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$isRegisterLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$registerLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.access$removeLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.getAccuracy (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.getCallbackHandle (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.getLocationRequest (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.initializeService (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.isRegisterLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerAfterBoot (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.removeLocator (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.setCallbackDispatcherHandle (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.setCallbackHandle (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.setDataCallback (BackgroundLocatorPlugin.java)
at rekab.app.background_locator.BootBroadcastReceiver.onReceive (BootBroadcastReceiver.java)
at android.app.ActivityThread.handleReceiver (ActivityThread.java:2838)
at android.app.ActivityThread.access$1700 (ActivityThread.java:178)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1547)
at android.os.Handler.dispatchMessage (Handler.java:111)
at android.os.Looper.loop (Looper.java:194)
at android.app.ActivityThread.main (ActivityThread.java:5637)
at java.lang.reflect.Method.invoke (Method.java)
at java.lang.reflect.Method.invoke (Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:754)

```

**Comment by WilliamFB** [comment]
I got a similar error:
It occurred on Android 10 (SDK 29), Android 9 (SDK 28), Android 6.0 (SDK 23) and Android 5.1 (SDK 22).
```
java.lang.RuntimeException: Unable to start receiver rekab.app.background_locator.BootBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3707)
  at android.app.ActivityThread.access$2000(ActivityThread.java:229)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:7331)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
  at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerLocator(BackgroundLocatorPlugin.kt:114)
  at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerAfterBoot(BackgroundLocatorPlugin.kt:307)
  at rekab.app.background_locator.BootBroadcastReceiver.onReceive(BootBroadcastReceiver.kt:11)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700)
```
It was happening on the device restart. I edited the line where the error was occuring (BackgroundLocatorPlugin.kt:114) to:
```
val initialDataMap = args[ARG_INIT_DATA_CALLBACK] as? Map<*, *>
```
It seems to be working but i am not sure if it can show other consequences. I will make a pull-request for this one.

**Comment by Wian-TMC** [comment]
@WilliamFB 
Awesome! Let's hope it won't cause other issues
