### ISSUE TITLE
on background service stop

### ISSUE THREAD

**Issue by jainsanket77** [rekab-app/background_locator#174]
```
W/ConnectionTracker(21372): Exception thrown while unbinding
W/ConnectionTracker(21372): java.lang.IllegalArgumentException: Service not registered: lu@77d4bfe
W/ConnectionTracker(21372): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
W/ConnectionTracker(21372): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
W/ConnectionTracker(21372): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(21372): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):1)
W/ConnectionTracker(21372): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):2)
W/ConnectionTracker(21372): 	at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):9)
W/ConnectionTracker(21372): 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker(21372): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker(21372): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(21372): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(21372): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):5)

```

**Comment by mehdok** [comment]
Hi @jainsanket77 
Thank you for opening an issue.

It would be nice if you could provide more info;

**Comment by mehdok** [comment]
Closing issue due to leak of information. Feel free to open it when more info is available;
