### ISSUE TITLE
No implementation found for io.flutter.view.FlutterCallbackInformation

### ISSUE THREAD

**Issue by WilliamFB** [rekab-app/background_locator#185]
I am having the following error, any suggestion?

Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for io.flutter.view.FlutterCallbackInformation io.flutter.embedding.engine.FlutterJNI.nativeLookupCallbackInformation(long) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeLookupCallbackInformation and Java_io_flutter_embedding_engine_FlutterJNI_nativeLookupCallbackInformation__J)
       at io.flutter.embedding.engine.FlutterJNI.nativeLookupCallbackInformation(FlutterJNI.java)
       at io.flutter.view.FlutterCallbackInformation.lookupCallbackInformation(FlutterCallbackInformation.java:30)
       at rekab.app.background_locator.LocatorService.startLocatorService(LocatorService.kt:81)
       at rekab.app.background_locator.LocatorService.onCreate(LocatorService.kt:69)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3380)
       at android.app.ActivityThread.-wrap4()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6548)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by mehdok** [comment]
Hi @WilliamFB 
Thank you for opening an issue;

Please share some code;

**Comment by WilliamFB** [comment]
This is the LocatorService.kt of the version i am using, the error occurs on line 81.

![Captura de tela de 2021-01-15 09-03-44](https://user-images.githubusercontent.com/41995692/104725562-054e2500-5711-11eb-8cea-4db53792f2c1.png)

**Comment by mehdok** [comment]
Did you set the callback in the `initialize` function?

**Comment by WilliamFB** [comment]
I think so, like this?

![image](https://user-images.githubusercontent.com/41995692/104729060-a095c900-5716-11eb-9455-a9ea2458eba6.png)

My version is at this point:
https://github.com/rekab-app/background_locator/tree/8190a64bbb4968c5ecdf41333234490360e9c12d

**Comment by mehdok** [comment]
You are  pointing to the library source code, show the usage in your code.
something like this:

````dart
BackgroundLocator.registerLocationUpdate(LocationCallbackHandler.callback,
````

**Comment by WilliamFB** [comment]
Is this happening because i am calling `startLocator` at the wrong moment? Obs: The crash only happens on a few devices.

![image](https://user-images.githubusercontent.com/41995692/104765963-85dc4800-5748-11eb-8371-b487e2f7ad18.png)
![image](https://user-images.githubusercontent.com/41995692/104766019-9d1b3580-5748-11eb-9705-0947164bee18.png)

**Comment by mehdok** [comment]
What do you mean by the wrong moment? Are you running the example app?

**Comment by WilliamFB** [comment]
Sorry @mehdok, i didn't want to say "wrong time", let's forget it. I will show some information below;

I am using bg_locator 1.2.2+1 and flutter 1.20.0;

My implementation is like the example, but there are some differences. I will show the differences after the implementation;


This is in my first screen `initState`:

![image](https://user-images.githubusercontent.com/41995692/105356685-7e96bd80-5bd2-11eb-84ec-e907bce99ea6.png)

![image](https://user-images.githubusercontent.com/41995692/105356409-2069da80-5bd2-11eb-80e3-e366b452ecc6.png)


The `registerLocationUpdate`:
![image](https://user-images.githubusercontent.com/41995692/105358690-45138180-5bd5-11eb-975b-6a789f0a4962.png)


Using the `unRegisterLocationUpdate`:
![image](https://user-images.githubusercontent.com/41995692/105359163-e3074c00-5bd5-11eb-8d96-b98c477101f6.png)

There are 2 differences:

 

- I don't use these two lines in my callback, because i send my location to a queue and i don't need to send it to my main Isolate:
`final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);`
`send?.send(locationDto);`

- I am not calling the functions in a separate class, like:
`LocationCallbackHandler.callback` or `LocationCallbackHandler.initCallback`
I just call them directly, because they are in the same file, like i showed in `registerLocationUpdate`.

**Comment by mehdok** [comment]
I'm not sure if this is the problem, but we have to eliminate its possibility :)

Your `callback` function must be `global` or `static`, is it?

**Comment by WilliamFB** [comment]
The callback is static, but anyway, i will separate the callback in a service. As soon as i know the results i tell you. Thanks!!

**Comment by mehdok** [comment]
While you are testing, it would be nice if you could test the example app to see if it's working for you or not, if the example app is working and your app doesn't, it would ease the debug process if you create a simple repository with your implementation;

**Comment by Johan07** [comment]
Same issue

**Comment by bayuly94** [comment]
same issue

**Comment by qwert2603** [comment]
Adding `FlutterInjector.instance().flutterLoader().ensureInitializationComplete(this, arrayOf())` has helped me.

**Comment by oligazar** [comment]
@mehdok 
I have the same issue on line `val callbackInfo = FlutterCallbackInformation.lookupCallbackInformation(callbackHandle)`

Registration for location updates, where `_onLocationData` is `static`: 
```
await BackgroundLocator.registerLocationUpdate(_onLocationData,
        initCallback: _onInitBackgroundLocation,
        initDataCallback: data,
        disposeCallback: _onDispose,
...
```

Has anybody found the reason and solution or workaround?

**Comment by rueichang** [comment]
I got the same issue even the example app.   This problem can be reproduced by rebooting the smart phone. 
I had installed the example app first.  Starting the service and ensure the service is running. Then I reboot the smart phone again and open the example app afterward. The APP will be crash and show the error message which is same as WilliamFB.  And APP won't be able to start properly...  My Android is 9.0..

**Comment by Trteich** [comment]
Any updates?
I've found that this crash appeares on app killing while service is running. As I investigated,  service tries to be recreated, and reffer to flutter part of app, but it is dead. Tried to return START_NON_STICKY from onStartComand(). It helpend on clean Android, but no effect on fu**ing Samsung. It seems like Samsung ignores START_NON_STICKY.

I'm completely not sure that my solution is right.

Also have an idea to cover all LocatorService.startLocatorService() into try/catch block, but it looks like a crutch

**Comment by Habil24** [comment]
Same issue

**Comment by M-Ali-D** [comment]
> Adding `FlutterInjector.instance().flutterLoader().ensureInitializationComplete(context, arrayOf())` has helped me.

It worked for me Thanks.

**Comment by Habil24** [comment]
> > Adding `FlutterInjector.instance().flutterLoader().ensureInitializationComplete(context, arrayOf())` has helped me.
> 
> It worked for me Thanks.

Hi, where should we add this line in our app?

**Comment by Habil24** [comment]
> Adding `FlutterInjector.instance().flutterLoader().ensureInitializationComplete(context, arrayOf())` has helped me.

Hi, where should we add this line in our app?

**Comment by mahira13** [comment]
> > Adding `FlutterInjector.instance().flutterLoader().ensureInitializationComplete(context, arrayOf())` has helped me.
> 
> Hi, where should we add this line in our app?

did you find where to add this line?

**Comment by williambarreiro** [comment]
I was using a very old version of the plugin, so i'm closing this issue. I recommend you take a look here: https://github.com/rekabhq/background_locator/issues/340
Since the package is no longer being updated, they forked it and fixed some common problems...
