### ISSUE TITLE
Android App crash on start (java.lang.RuntimeException: Unable to start service rekab.app.background_locator.IsolateHolderService)

### ISSUE THREAD

**Issue by atsumo** [rekab-app/background_locator#229]
use  version `1.6.0+1-beta`

It seems that ACTION_SHUTDOWN of onStartCommand is sometimes called before locatorClient is initialized....

```
 kotlin.UninitializedPropertyAccessException: lateinit property locatorClient has not been initialized
E/AndroidRuntime(18943): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
E/AndroidRuntime(18943): 	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
E/AndroidRuntime(18943): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
E/AndroidRuntime(18943): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18943): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(18943): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(18943): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18943): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(18943): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(18943): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property locatorClient has not been initialized
E/AndroidRuntime(18943): 	at rekab.app.background_locator.IsolateHolderService.shutdownHolderService(IsolateHolderService.kt:161)
E/AndroidRuntime(18943): 	at rekab.app.background_locator.IsolateHolderService.onStartCommand(IsolateHolderService.kt:117)
E/AndroidRuntime(18943): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
```

**Comment by hasitha3rd** [comment]
Any fix?

**Comment by atsumo** [comment]
It has been fixed #230
