### ISSUE TITLE
App crashes on unRegisterLocationUpdate

### ISSUE THREAD

**Issue by JanikoNaber** [rekab-app/background_locator#231]
Version: ^1.6.0+1-beta
Running on Android.
1) Start background_locator
2) Restart device (without restore on reboot)
=> isServiceRunning() = true
=> Location is not logging 
3) Stop background_locator (BackgroundLocator.unRegisterLocationUpdate())
=> App crashes with:
D/BackgroundLocatorPlugin(17788): Locator service is not running, nothing to stop
D/AndroidRuntime(17788): Shutting down VM
E/AndroidRuntime(17788): FATAL EXCEPTION: main
E/AndroidRuntime(17788): Process: app.example.mobile, PID: 17788
E/AndroidRuntime(17788): java.lang.RuntimeException: Unable to start service rekab.app.background_locator.IsolateHolderService@101a7e9 with Intent { act=SHUTDOWN cmp=app.example.mobile/rekab.app.background_locator.IsolateHolderService }: kotlin.UninitializedPropertyAccessException: lateinit property locatorClient has not been initialized
E/AndroidRuntime(17788): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4759)
E/AndroidRuntime(17788): 	at android.app.ActivityThread.access$2000(ActivityThread.java:301)
E/AndroidRuntime(17788): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2186)
E/AndroidRuntime(17788): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17788): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(17788): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(17788): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17788): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(17788): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(17788): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property locatorClient has not been initialized
E/AndroidRuntime(17788): 	at rekab.app.background_locator.IsolateHolderService.shutdownHolderService(IsolateHolderService.kt:161)
E/AndroidRuntime(17788): 	at rekab.app.background_locator.IsolateHolderService.onStartCommand(IsolateHolderService.kt:117)
E/AndroidRuntime(17788): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4741)
E/AndroidRuntime(17788): 	... 8 more
I/Process (17788): Sending signal. PID: 17788 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by elouiestudent** [comment]
We are also getting this issue with 1.5.0+1 on Android.

**Comment by BecoStopclub** [comment]
Version: ^1.6.0+1-beta
Running on Android.

Probably related: 

<pre><code>java.lang.UnsatisfiedLinkError: No implementation found for io.flutter.view.FlutterCallbackInformation io.flutter.embedding.engine.FlutterJNI.nativeLookupCallbackInformation(long) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeLookupCallbackInformation and Java_io_flutter_embedding_engine_FlutterJNI_nativeLookupCallbackInformation__J)
E/AndroidRuntime(19816): 	at io.flutter.embedding.engine.FlutterJNI.nativeLookupCallbackInformation(Native Method)
E/AndroidRuntime(19816): 	at io.flutter.view.FlutterCallbackInformation.lookupCallbackInformation(FlutterCallbackInformation.java:30)
E/AndroidRuntime(19816): 	at rekab.app.background_locator.IsolateHolderExtensionKt.startLocatorService(IsolateHolderExtension.kt:26)
E/AndroidRuntime(19816): 	at rekab.app.background_locator.IsolateHolderService.onCreate(IsolateHolderService.kt:57)
E/AndroidRuntime(19816): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
E/AndroidRuntime(19816): 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(19816): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
E/AndroidRuntime(19816): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19816): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(19816): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(19816): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19816): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(19816): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)</code></pre>

**Comment by Mohamed-512** [comment]
Experiencing same issue here as well :(

**Comment by marcusmvfa** [comment]
Any news about that?

**Comment by abedputra** [comment]
I think it has been fixed here
https://github.com/rekab-app/background_locator/pull/230
