### ISSUE TITLE
[ANDROID] java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by Wian-TMC** [rekab-app/background_locator#266]
Causes app to crash, but very seldom. Here are the app logs:

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at rekab.app.background_locator.BackgroundLocatorPlugin$Companion$sendResultWithDelay$$inlined$let$lambda$1.run(BackgroundLocatorPlugin.java:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

**Comment by mehdok** [comment]
Hi @Wian-TMC 
Thank you for opening an issue;

I'll look into it;

**Comment by argo1** [comment]
Found at least one case when this happens:
Created pull request #280
