### ISSUE TITLE
java.lang.IncompatibleClassChangeError: The method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)' was expected to be of type virtual but instead was found to be of type interface (declaration of 'rekab.app.background_locator.provider.GoogleLocationProviderClient' appears in /data/app/com.doa.lojisoft.saray-JqLCd0a12SEpAYQu6cUZjg==/base.apk:classes2.dex)

### ISSUE THREAD

**Issue by toprako** [rekab-app/background_locator#359]
Hello,

I get such an error when I integrate it in flutter.

Can you help me ??

java.lang.IncompatibleClassChangeError: The method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)' was expected to be of type virtual but instead was found to be of type interface (declaration of 'rekab.app.background_locator.provider.GoogleLocationProviderClient' appears in /data/app/com.doa.lojisoft.saray-JqLCd0a12SEpAYQu6cUZjg==/base.apk:classes2.dex)

**Comment by toprako** [comment]
Full Fail Message ;


E/AndroidRuntime(21264): java.lang.IncompatibleClassChangeError: The method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)' was expected to be of type virtual but instead was found to be of type interface (declaration of 'rekab.app.background_locator.provider.GoogleLocationProviderClient' appears in /data/app/com.doa.lojisoft.saray-JqLCd0a12SEpAYQu6cUZjg==/base.apk:classes2.dex)
E/AndroidRuntime(21264): 	at rekab.app.background_locator.provider.GoogleLocationProviderClient.requestLocationUpdates(GoogleLocationProviderClient.kt:17)
E/AndroidRuntime(21264): 	at rekab.app.background_locator.IsolateHolderService.startHolderService(IsolateHolderService.kt:156)
E/AndroidRuntime(21264): 	at rekab.app.background_locator.IsolateHolderService.onStartCommand(IsolateHolderService.kt:128)
E/AndroidRuntime(21264): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
E/AndroidRuntime(21264): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(21264): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
E/AndroidRuntime(21264): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(21264): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(21264): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime(21264): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21264): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(21264): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Alvish0407** [comment]
@toprako Use this https://pub.dev/packages/background_locator_2
