### ISSUE TITLE
Error add package 

### ISSUE THREAD

**Issue by gpibarra** [rekab-app/background_locator#5]
## Steps to Reproduce

1. Clone repo
2. Open proyect from example subfolder
3. Edit file pubspec.yaml
4. Add package "location: ^2.3.5"
5. Run app

**Expected results:**
Notification of background work

**Actual results:**
Exception

<details>
  <summary>Logs</summary>

```
[   +2 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Moto G 5 is available at: http://127.0.0.1:60354/iFpOkYs-vi4=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+6050 ms] D/AndroidRuntime( 6720): Shutting down VM
[ +164 ms] E/AndroidRuntime( 6720): FATAL EXCEPTION: main
[   +1 ms] E/AndroidRuntime( 6720): Process: rekab.app.background_locator_example, PID: 6720
[        ] E/AndroidRuntime( 6720): java.lang.RuntimeException: Unable to create service rekab.app.background_locator.LocatorService: java.lang.NullPointerException: Attempt to invoke
virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference
[        ] E/AndroidRuntime( 6720):     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3440)
[        ] E/AndroidRuntime( 6720):     at android.app.ActivityThread.-wrap4(Unknown Source:0)
[        ] E/AndroidRuntime( 6720):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
[        ] E/AndroidRuntime( 6720):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 6720):     at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime( 6720):     at android.app.ActivityThread.main(ActivityThread.java:6626)
[        ] E/AndroidRuntime( 6720):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 6720):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/AndroidRuntime( 6720):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[        ] E/AndroidRuntime( 6720): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object
reference
[        ] E/AndroidRuntime( 6720):     at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:50)
[        ] E/AndroidRuntime( 6720):     at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source:8)
[        ] E/AndroidRuntime( 6720):     at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:2)
[        ] E/AndroidRuntime( 6720):     at com.lyokone.location.FlutterLocation.setActivity(FlutterLocation.java:103)
[        ] E/AndroidRuntime( 6720):     at com.lyokone.location.LocationPlugin.registerWith(LocationPlugin.java:36)
[        ] E/AndroidRuntime( 6720):     at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
[   +3 ms] E/AndroidRuntime( 6720):     at rekab.app.background_locator_example.Application.registerWith(Application.kt:15)
[        ] E/AndroidRuntime( 6720):     at rekab.app.background_locator.LocatorService.startLocatorService(LocatorService.kt:80)
[        ] E/AndroidRuntime( 6720):     at rekab.app.background_locator.LocatorService.onCreate(LocatorService.kt:61)
[        ] E/AndroidRuntime( 6720):     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3430)
[        ] E/AndroidRuntime( 6720):     ... 8 more
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1039], locale es-419)
    • Flutter version 1.12.13+hotfix.8 at C:\develop\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\develop\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\gibarra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Moto G 5 • 192.168.0.5:5555 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

</details>

**Comment by mehdok** [comment]
I don't think this crash belongs to this library, you are adding a third party library and as you can see in crash log, it says `Attempt to invoke
virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference`. and you can not find `android.app.Activity.getMainLooper()` in this library.

**Comment by gpibarra** [comment]
In version 1.0.0+1 works fine.
Maybe it was fixed by changing "flutter plugin version 2".

**Comment by mehdok** [comment]
Glad it helped.
