### ISSUE TITLE
java.lang.IllegalArgumentException in firebase crashlytics and service getting closed in custom ROM devices

### ISSUE THREAD

**Issue by praveenbbhati** [rekab-app/background_locator#66]
This crash is reported hundred times on firebase crashlytics. The app is working fine but some time is getting crashed.

Does anyone face the same issue? or any solution?

FYI I've followed all steps suggested by wiki. 

**One more issue -**
The `IsolateHolderService` foreground service getting destroy in Chinese custom ROM devices like OnePlus, Xiaomi, Vivo, Huawei, etc. when the app gets removed from recent.  
 
![Capture](https://user-images.githubusercontent.com/10512037/82780555-3671a080-9e75-11ea-92c0-8ed841238c10.PNG)

**Stack trace** 

`Fatal Exception: java.lang.RuntimeException: Unable to start service rekab.app.background_locator.IsolateHolderService@e7be9cd with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3821)
       at android.app.ActivityThread.access$1800(ActivityThread.java:207)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

`Caused by java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
       at rekab.app.background_locator.IsolateHolderService.onStartCommand(:2)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3802)
       at android.app.ActivityThread.access$1800(ActivityThread.java:207)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by mehdok** [comment]
I'm aware of this issue and trying to find the problem;

**Comment by juanlabrador** [comment]
Same problem to me. When the app is dead and receive a notification.

**Comment by juanlabrador** [comment]
I think, in class IsolateHolderService, in the onStartCommand method, the intent params should be set null safety "?"

` override fun onStartCommand(intent: Intent, flags: Int, startId: Int) 
by  
override fun onStartCommand(intent: Intent?, flags: Int, startId: Int)`

And validate if is not null. Maybe works.

**Comment by juanlabrador** [comment]
And check in a class normal, and the method override in services should be -> 

` override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        return super.onStartCommand(intent, flags, startId)
    }`

**Comment by mehdok** [comment]
@praveenbbhati @juanlabrador Please test the new version to see if the problem is gone or not.
