### ISSUE TITLE
Store locations in database

### ISSUE THREAD

**Issue by Alystrasz** [rekab-app/background_locator#77]
Hello there,

I'm trying to store locations received by `background_locator` in a [database](https://pub.dev/packages/sqflite). I followed the plugin procedure described [here](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback) to import `com.tekartik.sqflite`, to be able to use it even when my app is closed.

However, database access is not working, as the following stacktrace is raised when a location is received:
```text
I/flutter (11181): database is now opened
E/flutter (11181): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(database_closed 1)
E/flutter (11181): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter (11181): <asynchronous suspension>
E/flutter (11181): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter (11181): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
E/flutter (11181): #3      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:383:14)
E/flutter (11181): #4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:327:22)
E/flutter (11181): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter (11181): #6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:323:33)
E/flutter (11181): #7      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite_common/src/database_mixin.dart:345:7)
E/flutter (11181): #8      SqfliteDatabaseMixin.txnRawInsert (package:sqflite_common/src/database_mixin.dart:382:12)
E/flutter (11181): #9      SqfliteDatabaseExecutorMixin.rawInsert (package:sqflite_common/src/database_mixin.dart:50:15)
E/flutter (11181): #10     SqfliteDatabaseExecutorMixin.insert (package:sqflite_common/src/database_mixin.dart:60:12)
E/flutter (11181): #11     AppDatabase.insertLocation (package:pandemia/data/database/database.dart:37:25)
E/flutter (11181): <asynchronous suspension>
E/flutter (11181): #12     Geolocator.callback (package:pandemia/utils/geolocation/Geolocator.dart:41:14)
E/flutter (11181): #13     callbackDispatcher.<anonymous closure> (package:background_locator/callback_dispatcher.dart:22:15)
E/flutter (11181): #14     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter (11181): #15     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter (11181): #16     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter (11181): #17     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter (11181): #18     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (11181): #19     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (11181): #20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (11181): #21     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter (11181): #22     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
```
Here is my callback:
```dart
static void callback(LocationDto locationDto) async {
  final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
  send?.send(locationDto);
  DateTime timestamp = new DateTime.fromMillisecondsSinceEpoch(locationDto.time.toInt());
  AppDatabase db = new AppDatabase();
  await db.insertLocation(
      new Location(
          lat: locationDto.latitude,
          lng: locationDto.longitude,
          timestamp: timestamp));
  print('received new location at $timestamp');
}
```
(please note that `db.insertLocation` ensures database is opened before trying to insert the actual location)
Did I forget to import something?

--- 
If you need to dig into the source code, here is my repository: https://github.com/Alystrasz/pandemia/tree/geolocation

The location callback is there: https://github.com/Alystrasz/pandemia/blob/geolocation/lib/utils/geolocation/Geolocator.dart
Database wrapper class is there: https://github.com/Alystrasz/pandemia/blob/geolocation/lib/data/database/database.dart

**Comment by mehdok** [comment]
It seems that you didn't open your database.
```
AppDatabase db = new AppDatabase();
await db.open();
  await db.insertLocation(
      new Location(
          lat: locationDto.latitude,
          lng: locationDto.longitude,
          timestamp: timestamp));
```

**Comment by Alystrasz** [comment]
I said in the issue that this was already done: `(please note that db.insertLocation ensures database is opened before trying to insert the actual location)`
Interestingly, I can't reproduce the issue on smartphones, it seems to appear only on my emulator.
