### ISSUE TITLE
java.lang.RuntimeException: Unable to start receiver rekab.app.background_locator.BootBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>       

### ISSUE THREAD

**Issue by juanlabrador** [rekab-app/background_locator#79]
Hi, This error occurs when you restart the phone in Android. 

Caused by kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
       at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerLocator(BackgroundLocatorPlugin.kt:101)
       at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerAfterBoot(BackgroundLocatorPlugin.kt:259)
       at rekab.app.background_locator.BootBroadcastReceiver.onReceive(BootBroadcastReceiver.kt:10)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3002)
       at android.app.ActivityThread.access$1800(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1526)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by adolfdsilva** [comment]
Getting same error in Crashlytics

**Comment by Alystrasz** [comment]
Hello, I have the exact same problem on [my application](https://github.com/Alystrasz/pandemia/tree/geolocation); it seems to crash when receiving the BOOT_COMPLETED signal.
Here's the complete stack trace:
```text
2020-07-15 13:31:35.013 4516-4516/? V/SmartcardService: main Received broadcast
2020-07-15 13:31:35.013 4516-4516/? V/SmartcardService: Starting smartcard service after boot completed
2020-07-15 13:31:35.032 2575-6533/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=12, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@60030c7)
2020-07-15 13:31:35.034 2575-3110/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=12, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
2020-07-15 13:31:35.036 2575-3751/? I/ActivityManager: Start proc 7449:fr.inria.pandemia/u0a138 for broadcast fr.inria.pandemia/rekab.app.background_locator.BootBroadcastReceiver
2020-07-15 13:31:35.042 7449-7449/? I/zygote64: Late-enabling -Xcheck:jni
2020-07-15 13:31:35.269 7449-7467/fr.inria.pandemia I/ResourceExtractor: Found extracted resources res_timestamp-1-1594811674268
2020-07-15 13:31:35.378 7449-7449/fr.inria.pandemia D/AndroidRuntime: Shutting down VM
2020-07-15 13:31:35.380 2575-3648/? I/ActivityManager: Finished processing BOOT_COMPLETED for u0
    
    --------- beginning of crash
2020-07-15 13:31:35.391 7449-7449/fr.inria.pandemia E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.inria.pandemia, PID: 7449
    java.lang.RuntimeException: Unable to start receiver rekab.app.background_locator.BootBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3294)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
        at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerLocator(BackgroundLocatorPlugin.kt:103)
        at rekab.app.background_locator.BackgroundLocatorPlugin$Companion.registerAfterBoot(BackgroundLocatorPlugin.kt:263)
        at rekab.app.background_locator.BootBroadcastReceiver.onReceive(BootBroadcastReceiver.kt:10)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3287)
        at android.app.ActivityThread.-wrap17(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6617) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769) 
2020-07-15 13:31:35.398 2575-3648/? I/ActivityManager: Start proc 7472:com.android.sprint.hiddenmenuapp/u0a39 for broadcast com.android.sprint.hiddenmenuapp/.MipLteVsncpErrorNotification
2020-07-15 13:31:35.400 2575-3648/? I/ActivityManager: Killing 5856:com.google.android.apps.tachyon/u0a90 (adj 906): empty #22
2020-07-15 13:31:35.412 2575-2659/? I/ActivityManager: Showing crash dialog for package fr.inria.pandemia u0
```

**Comment by Yukams** [comment]
Did you guys found out how to fix this issue ? I have the same problem when rebooting the android simulator :(
