### ISSUE TITLE
Periodically crashing app with given stacktrace

### ISSUE THREAD

**Issue by adolfdsilva** [rekab-app/background_locator#89]
AndroidRuntime  E  FATAL EXCEPTION: AsyncTask #6
                         E  Process: com.speanluy.speanloan.uat, PID: 9985
                         E  java.lang.RuntimeException: An error occurred while executing doInBackground()
                         E      at android.os.AsyncTask$3.done(AsyncTask.java:354)
                         E      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                         E      at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:764)
                         E  Caused by: java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { flg=0x10 cmp=com.speanluy.speanloan.uat/reka
                            b.app.background_locator.LocatorBroadcastReceiver (has extras) } dcount=1}
                         E      at android.app.job.JobParameters.completeWork(JobParameters.java:268)
                         E      at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
                         E      at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
                         E      at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
                         E      at android.os.AsyncTask$2.call(AsyncTask.java:333)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                         E      ... 3 more

**Comment by mehdok** [comment]
Can you share some code?

**Comment by nambv** [comment]
@mehdok I have exactly the same crash:

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { flg=0x10 cmp=com.snapmart.ridersdev/rekab.app.background_locator.LocatorBroadcastReceiver (has extras) } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:273)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:17)
       at androidx.core.app.JobIntentService$CommandProcessor.a(JobIntentService.java:17)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by nambv** [comment]
I found the stackoverflow issue with this crash:

https://stackoverflow.com/questions/52519946/java-lang-illegalargumentexception-given-work-is-not-active-exception-in-oreo-w

**Comment by mehdok** [comment]
Thank you @nambv, I'll look into it;

**Comment by nambv** [comment]
thanks @mehdok , hope it will be fixed soon 😄

**Comment by adolfdsilva** [comment]
Well I'm not exactly sure how the `JobIntentService` works, but is there a reason the JOB_ID is random?

I changed it to constant value and it's not crashing anymore.

`        private val JOB_ID = 99
`

**Comment by nambv** [comment]
@mehdok can you take a look at @adolfdsilva's  comment and update the lib version if it is solved? 😄

**Comment by mehdok** [comment]
@adolfdsilva @nambv 
I'm not really sure why I did that at that time. But if it fixes the problem please create a PR and I would be more than happy to merge it;

**Comment by nambv** [comment]
@mehdok in official docs with the example code job id is static, may be @adolfdsilva's solution will fix this issue:

https://developer.android.com/reference/androidx/core/app/JobIntentService

**Comment by mehdok** [comment]
@nambv Can you test that and confirm it is working?

**Comment by nambv** [comment]
@mehdok I have forked your repo to modify and test. Will give you the result soon :-?

**Comment by adolfdsilva** [comment]
@mehdok @nambv I had forked the lib earlier and tested it only on my device, it works fine.
I'm waiting for the update to go live on play store and if I don't see any crashes in firebase, I'll do a PR.
