### ISSUE TITLE
Error on detach

### ISSUE THREAD

**Issue by gpibarra** [rekab-app/background_locator#9]
## Steps to Reproduce

1. Clone repo (from master)
2. Open example proyect
3. Run flutter
4. Click Start button
5. Back button (from navigation bar Android)

**Expected results:** 
Stop background (if autostop: true), or stay in background (if autostop: false)

**Actual results:** 
Exception

<details>
  <summary>Logs</summary>

```
I/flutter (21853): Initialization done
I/OpenGLRenderer(21853): Initialized EGL, version 1.4
D/OpenGLRenderer(21853): Swap behavior 2
D/FlutterView(21853): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@297a492
D/FlutterView(21853): Already attached to this engine. Doing nothing.
I/Choreographer(21853): Skipped 30 frames!  The application may be doing too much work on its main thread.
D/vndksupport(21853): Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport(21853): Loading /vendor/lib/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
E/AccessibilityBridge(21853): VirtualView node must not be the root node.
I/flutter (21853): location in dart: LocationDto{latitude: -34.6524895, longitude: -58.5683421, accuracy: 15.871999740600586, altitude: 44.89999771118164, speed: 0.0, speedAccuracy: 0.0, heading: 0.0}
E/AccessibilityBridge(21853): VirtualView node must not be the root node.
E/AccessibilityBridge(21853): VirtualView node must not be the root node.
D/FlutterView(21853): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@297a492
D/FlutterActivityAndFragmentDelegate(21853): Detaching FlutterEngine from the Activity that owns this Fragment.
D/FlutterEngine(21853): Destroying.
D/FlutterEnginePluginRegistry(21853): Destroying.
D/AndroidRuntime(21853): Shutting down VM
E/AndroidRuntime(21853): FATAL EXCEPTION: main
E/AndroidRuntime(21853): Process: rekab.app.background_locator_example, PID: 21853
E/AndroidRuntime(21853): java.lang.RuntimeException: Unable to destroy activity {rekab.app.background_locator_example/rekab.app.background_locator_example.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property locatorClient has not been initialized
E/AndroidRuntime(21853): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4497)
E/AndroidRuntime(21853): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
E/AndroidRuntime(21853): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime(21853): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
E/AndroidRuntime(21853): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21853): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(21853): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
E/AndroidRuntime(21853): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21853): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(21853): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
E/AndroidRuntime(21853): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property locatorClient has not been initialized
E/AndroidRuntime(21853): 	at rekab.app.background_locator.BackgroundLocatorPlugin.onDetachedFromEngine(BackgroundLocatorPlugin.kt:212)
E/AndroidRuntime(21853): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:244)
E/AndroidRuntime(21853): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime(21853): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime(21853): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:116)
E/AndroidRuntime(21853): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:267)
E/AndroidRuntime(21853): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:468)
E/AndroidRuntime(21853): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:588)
E/AndroidRuntime(21853): 	at android.app.Activity.performDestroy(Activity.java:7241)
E/AndroidRuntime(21853): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1271)
E/AndroidRuntime(21853): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4484)
E/AndroidRuntime(21853): 	... 9 more
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1039], locale es-419)
    • Flutter version 1.12.13+hotfix.8 at C:\develop\flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\develop\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\gibarra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Moto G 5 • ZY32226G73       • android-arm • Android 8.1.0 (API 27)
    • Moto G 5 • 192.168.0.5:5555 • android-arm • Android 8.1.0 (API 27)

• No issues found!

```

</details>

**Comment by gpibarra** [comment]
In android\src\main\kotlin\rekab\app\background_locator\BackgroundLocatorPlugin.kt:202 
Context is null

**Comment by TheMisir** [comment]
I have same issue, when user closes app using launcher. This happening and app locator service stops.

```
E/AndroidRuntime( 4479): java.lang.RuntimeException: Unable to destroy activity {com.fonibo.deliver/com.fonibo.deliver.MainActivity}: kotlin.KotlinNullPointerException
E/AndroidRuntime( 4479): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4480)
E/AndroidRuntime( 4479): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4498)
E/AndroidRuntime( 4479): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
E/AndroidRuntime( 4479): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime( 4479): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime( 4479): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
E/AndroidRuntime( 4479): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4479): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 4479): 	at android.app.ActivityThread.main(ActivityThread.java:6762)
E/AndroidRuntime( 4479): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4479): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 4479): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 4479): Caused by: kotlin.KotlinNullPointerException
E/AndroidRuntime( 4479): 	at rekab.app.background_locator.BackgroundLocatorPlugin.onDetachedFromEngine(BackgroundLocatorPlugin.kt:217)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:268)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:112)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:290)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:500)
E/AndroidRuntime( 4479): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:568)
E/AndroidRuntime( 4479): 	at android.app.Activity.performDestroy(Activity.java:7395)
E/AndroidRuntime( 4479): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
E/AndroidRuntime( 4479): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4465)
E/AndroidRuntime( 4479): 	... 11 more
```
